export const ASSET_LIST_REQUEST = "ASSET_LIST_REQUEST";
export const ASSET_LIST_SUCCESS = "ASSET_LIST_SUCCESS";
export const ASSET_LIST_FAIL = "ASSET_LIST_FAIL";

export const ASSET_DETAILS_REQUEST = "ASSET_DETAILS_REQUEST";
export const ASSET_DETAILS_SUCCESS = "ASSET_DETAILS_SUCCESS";
export const ASSET_DETAILS_FAIL = "ASSET_DETAILS_FAIL";

export const ASSET_CREATE_REQUEST = 'ASSET_CREATE_REQUEST';
export const ASSET_CREATE_SUCCESS = 'ASSET_CREATE_SUCCESS';
export const ASSET_CREATE_FAIL = 'ASSET_CREATE_FAIL';
export const ASSET_CREATE_RESET = 'ASSET_CREATE_RESET';

export const ASSET_SCREEN_CREATE_REQUEST = 'ASSET_SCREEN_CREATE_REQUEST';
export const ASSET_SCREEN_CREATE_SUCCESS = 'ASSET_SCREEN_CREATE_SUCCESS';
export const ASSET_SCREEN_CREATE_FAIL = 'ASSET_SCREEN_CREATE_FAIL';
export const ASSET_SCREEN_CREATE_RESET = 'ASSET_SCREEN_CREATE_RESET';

export const ASSET_REVIEW_CREATE_REQUEST = 'ASSET_REVIEW_CREATE_REQUEST';
export const ASSET_REVIEW_CREATE_SUCCESS = 'ASSET_REVIEW_CREATE_SUCCESS';
export const ASSET_REVIEW_CREATE_FAIL = 'ASSET_REVIEW_CREATE_FAIL';
export const ASSET_REVIEW_CREATE_RESET = 'ASSET_REVIEW_CREATE_RESET';

export const ASSET_UPDATE_REQUEST = 'ASSET_UPDATE_REQUEST';
export const ASSET_UPDATE_SUCCESS = 'ASSET_UPDATE_SUCCESS';
export const ASSET_UPDATE_FAIL = 'ASSET_UPDATE_FAIL';
export const ASSET_UPDATE_RESET = 'ASSET_UPDATE_RESET';

export const ASSET_DELETE_REQUEST = 'ASSET_DELETE_REQUEST';
export const ASSET_DELETE_SUCCESS = 'ASSET_DELETE_SUCCESS';
export const ASSET_DELETE_FAIL = 'ASSET_DELETE_FAIL';
export const ASSET_DELETE_RESET = 'ASSET_DELETE_RESET';

export const ASSET_CATEGORY_LIST_REQUEST = 'ASSET_CATEGORY_LIST_REQUEST';
export const ASSET_CATEGORY_LIST_SUCCESS = 'ASSET_CATEGORY_LIST_SUCCESS';
export const ASSET_CATEGORY_LIST_FAIL = 'ASSET_CATEGORY_LIST_FAIL';

export const ASSET_SCREENS_REQUEST = 'ASSET_SCREENS_REQUEST';
export const ASSET_SCREENS_SUCCESS = 'ASSET_SCREENS_SUCCESS';
export const ASSET_SCREENS_FAIL = 'ASSET_SCREENS_FAIL';

export const ASSET_LIKE_REQUEST = 'ASSET_LIKE_REQUEST';
export const ASSET_LIKE_SUCCESS = 'ASSET_LIKE_SUCCESS';
export const ASSET_LIKE_FAIL = 'ASSET_LIKE_FAIL';

export const ASSET_UNLIKE_REQUEST = 'ASSET_UNLIKE_REQUEST';
export const ASSET_UNLIKE_SUCCESS = 'ASSET_UNLIKE_SUCCESS';
export const ASSET_UNLIKE_FAIL = 'ASSET_UNLIKE_FAIL';

export const ASSET_FLAG_REQUEST = 'ASSET_FLAG_REQUEST';
export const ASSET_FLAG_SUCCESS = 'ASSET_FLAG_SUCCESS';
export const ASSET_FLAG_FAIL = 'ASSET_FLAG_FAIL';

export const ASSET_PARAMS_REQUEST = 'ASSET_PARAMS_REQUEST';
export const ASSET_PARAMS_SUCCESS = 'ASSET_PARAMS_SUCCESS';
export const ASSET_PARAMS_FAIL = 'ASSET_PARAMS_FAIL';
