export const ASSET_CALENDER_REQUEST = 'ASSET_CALENDER_REQUEST';
export const ASSET_CALENDER_SUCCESS = 'ASSET_CALENDER_SUCCESS';
export const ASSET_CALENDER_FAIL = 'ASSET_CALENDER_FAIL';

export const SCREEN_CALENDER_REQUEST = 'SCREEN_CALENDER_REQUEST';
export const SCREEN_CALENDER_SUCCESS = 'SCREEN_CALENDER_SUCCESS';
export const SCREEN_CALENDER_FAIL = 'SCREEN_CALENDER_FAIL';

export const ADD_CALENDER_DATA_REQUEST = 'ADD_CALENDER_DATA_REQUEST';
export const ADD_CALENDER_DATA_SUCCESS = 'ADD_CALENDER_DATA_SUCCESS';
export const ADD_CALENDER_DATA_FAIL = 'ADD_CALENDER_DATA_FAIL';

export const BOOK_SLOT_REQUEST = 'BOOK_SLOT_REQUEST';
export const BOOK_SLOT_SUCCESS = 'BOOK_SLOT_SUCCESS';
export const BOOK_SLOT_FAIL = 'BOOK_SLOT_FAIL';

export const BOOK_DAY_SLOT_REQUEST = 'BOOK_DAY_SLOT_REQUEST';
export const BOOK_DAY_SLOT_SUCCESS = 'BOOK_DAY_SLOT_SUCCESS';
export const BOOK_DAY_SLOT_FAIL = 'BOOK_DAY_SLOT_FAIL';

export const BOOK_DAY_REQUEST = 'BOOK_DAY_REQUEST';
export const BOOK_DAY_SUCCESS = 'BOOK_DAY_SUCCESS';
export const BOOK_DAY_FAIL = 'BOOK_DAY_FAIL';
