export const CHANNEL_LIST_REQUEST = "CHANNEL_LIST_REQUEST";
export const CHANNEL_LIST_SUCCESS = "CHANNEL_LIST_SUCCESS";
export const CHANNEL_LIST_FAIL = "CHANNEL_LIST_FAIL";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";

export const CHANNEL_CREATE_REQUEST = 'CHANNEL_CREATE_REQUEST';
export const CHANNEL_CREATE_SUCCESS = 'CHANNEL_CREATE_SUCCESS';
export const CHANNEL_CREATE_FAIL = 'CHANNEL_CREATE_FAIL';
export const CHANNEL_CREATE_RESET = 'CHANNEL_CREATE_RESET';

export const CHANNEL_REVIEW_CREATE_REQUEST = 'CHANNEL_REVIEW_CREATE_REQUEST';
export const CHANNEL_REVIEW_CREATE_SUCCESS = 'CHANNEL_REVIEW_CREATE_SUCCESS';
export const CHANNEL_REVIEW_CREATE_FAIL = 'CHANNEL_REVIEW_CREATE_FAIL';
export const CHANNEL_REVIEW_CREATE_RESET = 'CHANNEL_REVIEW_CREATE_RESET';

export const CHANNEL_UPDATE_REQUEST = 'CHANNEL_UPDATE_REQUEST';
export const CHANNEL_UPDATE_SUCCESS = 'CHANNEL_UPDATE_SUCCESS';
export const CHANNEL_UPDATE_FAIL = 'CHANNEL_UPDATE_FAIL';
export const CHANNEL_UPDATE_RESET = 'CHANNEL_UPDATE_RESET';

export const CHANNEL_DELETE_REQUEST = 'CHANNEL_DELETE_REQUEST';
export const CHANNEL_DELETE_SUCCESS = 'CHANNEL_DELETE_SUCCESS';
export const CHANNEL_DELETE_FAIL = 'CHANNEL_DELETE_FAIL';
export const CHANNEL_DELETE_RESET = 'CHANNEL_DELETE_RESET';

export const CHANNEL_CATEGORY_LIST_REQUEST = 'CHANNEL_CATEGORY_LIST_REQUEST';
export const CHANNEL_CATEGORY_LIST_SUCCESS = 'CHANNEL_CATEGORY_LIST_SUCCESS';
export const CHANNEL_CATEGORY_LIST_FAIL = 'CHANNEL_CATEGORY_LIST_FAIL';

export const CHANNEL_FILMS_REQUEST = 'CHANNEL_FILMS_REQUEST';
export const CHANNEL_FILMS_SUCCESS = 'CHANNEL_FILMS_SUCCESS';
export const CHANNEL_FILMS_FAIL = 'CHANNEL_FILMS_FAIL';

export const CHANNEL_FILM_UPLOAD_REQUEST = 'CHANNEL_FILM_UPLOAD_REQUEST';
export const CHANNEL_FILM_UPLOAD_SUCCESS = 'CHANNEL_FILM_UPLOAD_SUCCESS';
export const CHANNEL_FILM_UPLOAD_FAIL = 'CHANNEL_FILM_UPLOAD_FAIL';

export const CHANNEL_FILM_DELETE_REQUEST = 'CHANNEL_FILM_DELETE_REQUEST';
export const CHANNEL_FILM_DELETE_SUCCESS = 'CHANNEL_FILM_DELETE_SUCCESS';
export const CHANNEL_FILM_DELETE_FAIL = 'CHANNEL_FILM_DELETE_FAIL';

export const CHANNEL_LIKE_REQUEST = 'CHANNEL_LIKE_REQUEST';
export const CHANNEL_LIKE_SUCCESS = 'CHANNEL_LIKE_SUCCESS';
export const CHANNEL_LIKE_FAIL = 'CHANNEL_LIKE_FAIL';

export const CHANNEL_UNLIKE_REQUEST = 'CHANNEL_UNLIKE_REQUEST';
export const CHANNEL_UNLIKE_SUCCESS = 'CHANNEL_UNLIKE_SUCCESS';
export const CHANNEL_UNLIKE_FAIL = 'CHANNEL_UNLIKE_FAIL';

export const CHANNEL_SUBSCRIBE_REQUEST = 'CHANNEL_SUBSCRIBE_REQUEST';
export const CHANNEL_SUBSCRIBE_SUCCESS = 'CHANNEL_SUBSCRIBE_SUCCESS';
export const CHANNEL_SUBSCRIBE_FAIL = 'CHANNEL_SUBSCRIBE_FAIL';

export const CHANNEL_UNSUBSCRIBE_REQUEST = 'CHANNEL_UNSUBSCRIBE_REQUEST';
export const CHANNEL_UNSUBSCRIBE_SUCCESS = 'CHANNEL_UNSUBSCRIBE_SUCCESS';
export const CHANNEL_UNSUBSCRIBE_FAIL = 'CHANNEL_UNSUBSCRIBE_FAIL';

export const CHANNEL_FLAG_REQUEST = 'CHANNEL_FLAG_REQUEST';
export const CHANNEL_FLAG_SUCCESS = 'CHANNEL_FLAG_SUCCESS';
export const CHANNEL_FLAG_FAIL = 'CHANNEL_FLAG_FAIL';

export const CHANNEL_PARAMS_REQUEST = 'CHANNEL_PARAMS_REQUEST';
export const CHANNEL_PARAMS_SUCCESS = 'CHANNEL_PARAMS_SUCCESS';
export const CHANNEL_PARAMS_FAIL = 'CHANNEL_PARAMS_FAIL';


