export const FILM_LIST_REQUEST = 'FILM_LIST_REQUEST';
export const FILM_LIST_SUCCESS = 'FILM_LIST_SUCCESS';
export const FILM_LIST_FAIL = 'FILM_LIST_FAIL';

export const FILM_DETAILS_REQUEST = 'FILM_DETAILS_REQUEST';
export const FILM_DETAILS_SUCCESS = 'FILM_DETAILS_SUCCESS';
export const FILM_DETAILS_FAIL = 'FILM_DETAILS_FAIL';

export const FILM_DELETE_REQUEST = 'FILM_DELETE_REQUEST';
export const FILM_DELETE_SUCCESS = 'FILM_DELETE_SUCCESS';
export const FILM_DELETE_FAIL = 'FILM_DELETE_FAIL';
export const FILM_DELETE_RESET = 'FILM_DELETE_RESET';

export const LIKE_FILM_REQUEST = 'LIKE_FILM_REQUEST';
export const LIKE_FILM_SUCCESS = 'LIKE_FILM_SUCCESS';
export const LIKE_FILM_FAIL = 'LIKE_FILM_FAIL';

export const UNLIKE_FILM_REQUEST = 'LIKE_FILM_REQUEST';
export const UNLIKE_FILM_SUCCESS = 'LIKE_FILM_SUCCESS';
export const UNLIKE_FILM_FAIL = 'LIKE_FILM_FAIL';

export const REVIEW_FILM_REQUEST = 'REVIEW_FILM_REQUEST';
export const REVIEW_FILM_SUCCESS = 'REVIEW_FILM_SUCCESS';
export const REVIEW_FILM_FAIL = 'REVIEW_FILM_FAIL';
export const REVIEW_FILM_RESET = 'REVIEW_FILM_RESET';

export const VIEWS_FILM_REQUEST = 'VIEWS_FILM_REQUEST';
export const VIEWS_FILM_SUCCESS = 'VIEWS_FILM_SUCCESS';
export const VIEWS_FILM_FAIL = 'VIEWS_FILM_FAIL';

export const FILM_UPDATE_REQUEST = 'FILM_UPDATE_REQUEST';
export const FILM_UPDATE_SUCCESS = 'FILM_UPDATE_SUCCESS';
export const FILM_UPDATE_FAIL = 'FILM_UPDATE_FAIL';
export const FILM_UPDATE_RESET = 'FILM_UPDATE_RESET';

export const FILM_PARAMS_REQUEST = 'FILM_PARAMS_REQUEST';
export const FILM_PARAMS_SUCCESS = 'FILM_PARAMS_SUCCESS';
export const FILM_PARAMS_FAIL = 'FILM_PARAMS_FAIL';

export const FILM_FLAG_REQUEST = 'FILM_FLAG_REQUEST';
export const FILM_FLAG_SUCCESS = 'FILM_FLAG_SUCCESS';
export const FILM_FLAG_FAIL = 'FILM_FLAG_FAIL';