export const CREATE_SCREEN_GAME_REQUEST = "CREATE_SCREEN_GAME_REQUEST";
export const CREATE_SCREEN_GAME_SUCCESS = "CREATE_SCREEN_GAME_SUCCESS";
export const CREATE_SCREEN_GAME_FAIL = "CREATE_SCREEN_GAME_FAIL";

export const REMOVE_SCREEN_GAME_REQUEST = "REMOVE_SCREEN_GAME_REQUEST";
export const REMOVE_SCREEN_GAME_SUCCESS = "REMOVE_SCREEN_GAME_SUCCESS";
export const REMOVE_SCREEN_GAME_FAIL = "REMOVE_SCREEN_GAME_FAIL";

export const DETAILS_SCREEN_GAME_REQUEST = "DETAILS_SCREEN_GAME_REQUEST";
export const DETAILS_SCREEN_GAME_SUCCESS = "DETAILS_SCREEN_GAME_SUCCESS";
export const DETAILS_SCREEN_GAME_FAIL = "DETAILS_SCREEN_GAME_FAIL";

export const PLAY_SCREEN_GAME_REQUEST = "PLAY_SCREEN_GAME_REQUEST";
export const PLAY_SCREEN_GAME_SUCCESS = "PLAY_SCREEN_GAME_SUCCESS";
export const PLAY_SCREEN_GAME_FAIL = "PLAY_SCREEN_GAME_FAIL";


export const CREATE_ASSET_GAME_REQUEST = "CREATE_ASSET_GAME_REQUEST";
export const CREATE_ASSET_GAME_SUCCESS = "CREATE_ASSET_GAME_SUCCESS";
export const CREATE_ASSET_GAME_FAIL = "CREATE_ASSET_GAME_FAIL";

export const REMOVE_ASSET_GAME_REQUEST = "REMOVE_ASSET_GAME_REQUEST";
export const REMOVE_ASSET_GAME_SUCCESS = "REMOVE_ASSET_GAME_SUCCESS";
export const REMOVE_ASSET_GAME_FAIL = "REMOVE_ASSET_GAME_FAIL";

export const DETAILS_ASSET_GAME_REQUEST = "DETAILS_ASSET_GAME_REQUEST";
export const DETAILS_ASSET_GAME_SUCCESS = "DETAILS_ASSET_GAME_SUCCESS";
export const DETAILS_ASSET_GAME_FAIL = "DETAILS_ASSET_GAME_FAIL";

export const PLAY_ASSET_GAME_REQUEST = "PLAY_ASSET_GAME_REQUEST";
export const PLAY_ASSET_GAME_SUCCESS = "PLAY_ASSET_GAME_SUCCESS";
export const PLAY_ASSET_GAME_FAIL = "PLAY_ASSET_GAME_FAIL";


export const CREATE_ADVERT_GAME_REQUEST = "CREATE_ADVERT_GAME_GAME_REQUEST";
export const CREATE_ADVERT_GAME_SUCCESS = "CREATE_ADVERT_GAME_GAME_SUCCESS";
export const CREATE_ADVERT_GAME_FAIL = "CREATE_ADVERT_GAME_GAME_FAIL";

export const REMOVE_ADVERT_GAME_REQUEST = "REMOVE_ADVERT_GAME_GAME_REQUEST";
export const REMOVE_ADVERT_GAME_SUCCESS = "REMOVE_ADVERT_GAME_GAME_SUCCESS";
export const REMOVE_ADVERT_GAME_FAIL = "REMOVE_ADVERT_GAME_GAME_FAIL";

export const DETAILS_ADVERT_GAME_REQUEST = "DETAILS_ADVERT_GAME_GAME_REQUEST";
export const DETAILS_ADVERT_GAME_SUCCESS = "DETAILS_ADVERT_GAME_GAME_SUCCESS";
export const DETAILS_ADVERT_GAME_FAIL = "DETAILS_ADVERT_GAME_GAME_FAIL";

export const PLAY_ADVERT_GAME_REQUEST = "PLAY_ADVERT_GAME_REQUEST";
export const PLAY_ADVERT_GAME_SUCCESS = "PLAY_ADVERT_GAME_SUCCESS";
export const PLAY_ADVERT_GAME_FAIL = "PLAY_ADVERT_GAME_FAIL";


export const CREATE_CHANNEL_GAME_REQUEST = "CREATE_CHANNEL_GAME_REQUEST";
export const CREATE_CHANNEL_GAME_SUCCESS = "CREATE_CHANNEL_GAME_SUCCESS";
export const CREATE_CHANNEL_GAME_FAIL = "CREATE_CHANNEL_GAME_FAIL";

export const REMOVE_CHANNEL_GAME_REQUEST = "REMOVE_CHANNEL_GAME_REQUEST";
export const REMOVE_CHANNEL_GAME_SUCCESS = "REMOVE_CHANNEL_GAME_SUCCESS";
export const REMOVE_CHANNEL_GAME_FAIL = "REMOVE_CHANNEL_GAME_FAIL";

export const DETAILS_CHANNEL_GAME_REQUEST = "DETAILS_CHANNEL_GAME_REQUEST";
export const DETAILS_CHANNEL_GAME_SUCCESS = "DETAILS_CHANNEL_GAME_SUCCESS";
export const DETAILS_CHANNEL_GAME_FAIL = "DETAILS_CHANNEL_GAME_FAIL";

export const PLAY_CHANNEL_GAME_REQUEST = "PLAY_CHANNEL_GAME_REQUEST";
export const PLAY_CHANNEL_GAME_SUCCESS = "PLAY_CHANNEL_GAME_SUCCESS";
export const PLAY_CHANNEL_GAME_FAIL = "PLAY_CHANNEL_GAME_FAIL";


export const CREATE_FILM_GAME_REQUEST = "CREATE_FILM_GAME_GAME_REQUEST";
export const CREATE_FILM_GAME_SUCCESS = "CREATE_FILM_GAME_GAME_SUCCESS";
export const CREATE_FILM_GAME_FAIL = "CREATE_FILM_GAME_GAME_FAIL";

export const REMOVE_FILM_GAME_REQUEST = "REMOVE_FILM_GAME_GAME_REQUEST";
export const REMOVE_FILM_GAME_SUCCESS = "REMOVE_FILM_GAME_GAME_SUCCESS";
export const REMOVE_FILM_GAME_FAIL = "REMOVE_FILM_GAME_GAME_FAIL";

export const DETAILS_FILM_GAME_REQUEST = "DETAILS_FILM_GAME_GAME_REQUEST";
export const DETAILS_FILM_GAME_SUCCESS = "DETAILS_FILM_GAME_GAME_SUCCESS";
export const DETAILS_FILM_GAME_FAIL = "DETAILS_FILM_GAME_GAME_FAIL";

export const PLAY_FILM_GAME_REQUEST = "PLAY_FILM_GAME_REQUEST";
export const PLAY_FILM_GAME_SUCCESS = "PLAY_FILM_GAME_SUCCESS";
export const PLAY_FILM_GAME_FAIL = "PLAY_FILM_GAME_FAIL";


export const CREATE_SHOP_GAME_REQUEST = "CREATE_SHOP_GAME_REQUEST";
export const CREATE_SHOP_GAME_SUCCESS = "CREATE_SHOP_GAME_SUCCESS";
export const CREATE_SHOP_GAME_FAIL = "CREATE_SHOP_GAME_FAIL";

export const REMOVE_SHOP_GAME_REQUEST = "REMOVE_SHOP_GAME_REQUEST";
export const REMOVE_SHOP_GAME_SUCCESS = "REMOVE_SHOP_GAME_SUCCESS";
export const REMOVE_SHOP_GAME_FAIL = "REMOVE_SHOP_GAME_FAIL";

export const DETAILS_SHOP_GAME_REQUEST = "DETAILS_SHOP_GAME_REQUEST";
export const DETAILS_SHOP_GAME_SUCCESS = "DETAILS_SHOP_GAME_SUCCESS";
export const DETAILS_SHOP_GAME_FAIL = "DETAILS_SHOP_GAME_FAIL";

export const PLAY_SHOP_GAME_REQUEST = "PLAY_SHOP_GAME_REQUEST";
export const PLAY_SHOP_GAME_SUCCESS = "PLAY_SHOP_GAME_SUCCESS";
export const PLAY_SHOP_GAME_FAIL = "PLAY_SHOP_GAME_FAIL";


export const CREATE_ITEM_GAME_REQUEST = "CREATE_ITEM_GAME_GAME_REQUEST";
export const CREATE_ITEM_GAME_SUCCESS = "CREATE_ITEM_GAME_GAME_SUCCESS";
export const CREATE_ITEM_GAME_FAIL = "CREATE_ITEM_GAME_GAME_FAIL";

export const REMOVE_ITEM_GAME_REQUEST = "REMOVE_ITEM_GAME_GAME_REQUEST";
export const REMOVE_ITEM_GAME_SUCCESS = "REMOVE_ITEM_GAME_GAME_SUCCESS";
export const REMOVE_ITEM_GAME_FAIL = "REMOVE_ITEM_GAME_GAME_FAIL";

export const DETAILS_ITEM_GAME_REQUEST = "DETAILS_ITEM_GAME_GAME_REQUEST";
export const DETAILS_ITEM_GAME_SUCCESS = "DETAILS_ITEM_GAME_GAME_SUCCESS";
export const DETAILS_ITEM_GAME_FAIL = "DETAILS_ITEM_GAME_GAME_FAIL";

export const PLAY_ITEM_GAME_REQUEST = "PLAY_ITEM_GAME_REQUEST";
export const PLAY_ITEM_GAME_SUCCESS = "PLAY_ITEM_GAME_SUCCESS";
export const PLAY_ITEM_GAME_FAIL = "PLAY_ITEM_GAME_FAIL";