export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL';

export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL';
export const ITEM_DELETE_RESET = 'ITEM_DELETE_RESET';

export const LIKE_ITEM_REQUEST = 'LIKE_ITEM_REQUEST';
export const LIKE_ITEM_SUCCESS = 'LIKE_ITEM_SUCCESS';
export const LIKE_ITEM_FAIL = 'LIKE_ITEM_FAIL';

export const UNLIKE_ITEM_REQUEST = 'LIKE_ITEM_REQUEST';
export const UNLIKE_ITEM_SUCCESS = 'LIKE_ITEM_SUCCESS';
export const UNLIKE_ITEM_FAIL = 'LIKE_ITEM_FAIL';

export const REVIEW_ITEM_REQUEST = 'REVIEW_ITEM_REQUEST';
export const REVIEW_ITEM_SUCCESS = 'REVIEW_ITEM_SUCCESS';
export const REVIEW_ITEM_FAIL = 'REVIEW_ITEM_FAIL';
export const REVIEW_ITEM_RESET = 'REVIEW_ITEM_RESET';


export const VIEWS_ITEM_REQUEST = 'VIEWS_ITEM_REQUEST';
export const VIEWS_ITEM_SUCCESS = 'VIEWS_ITEM_SUCCESS';
export const VIEWS_ITEM_FAIL = 'VIEWS_ITEM_FAIL';

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL';

export const ITEM_BUY_REQUEST = 'ITEM_BUY_REQUEST';
export const ITEM_BUY_SUCCESS = 'ITEM_BUY_SUCCESS';
export const ITEM_BUY_FAIL = 'ITEM_BUY_FAIL';