export const PIN_GET_REQUEST = "PIN_GET_REQUEST";
export const PIN_GET_SUCCESS = "PIN_GET_SUCCESS";
export const PIN_GET_FAIL = "PIN_GET_FAIL";

export const PIN_ADD_REQUEST = "PIN_ADD_REQUEST";
export const PIN_ADD_SUCCESS = "PIN_ADD_SUCCESS";
export const PIN_ADD_FAIL = "PIN_ADD_FAIL";
export const PIN_ADD_RESET = "PIN_ADD_RESET";

export const PIN_UPDATE_REQUEST = "PIN_UPDATE_REQUEST";
export const PIN_UPDATE_SUCCESS = "PIN_UPDATE_SUCCESS";
export const PIN_UPDATE_FAIL = "PIN_UPDATE_FAIL";
export const PIN_UPDATE_RESET = "PIN_UPDATE_RESET";

