export const MASTER_REQUEST_REQUEST = 'MASTER_REQUEST_REQUEST';
export const MASTER_REQUEST_SUCCESS = 'MASTER_REQUEST_SUCCESS';
export const MASTER_REQUEST_FAIL = 'MASTER_REQUEST_FAIL';

export const ALLY_REQUEST_REQUEST = 'ALLY_REQUEST_REQUEST';
export const ALLY_REQUEST_SUCCESS = 'ALLY_REQUEST_SUCCESS';
export const ALLY_REQUEST_FAIL = 'ALLY_REQUEST_FAIL';

export const BRAND_REQUEST_REQUEST = 'BRAND_REQUEST_REQUEST';
export const BRAND_REQUEST_SUCCESS = 'BRAND_REQUEST_SUCCESS';
export const BRAND_REQUEST_FAIL = 'BRAND_REQUEST_FAIL';

export const ALL_PLEA_LIST_REQUEST = 'ALL_PLEA_LIST_REQUEST';
export const ALL_PLEA_LIST_SUCCESS = 'ALL_PLEA_LIST_SUCCESS';
export const ALL_PLEA_LIST_FAIL = 'ALL_PLEA_LIST_FAIL';

export const PLEA_SUMMARY_REQUEST = 'PLEA_SUMMARY_REQUEST';
export const PLEA_SUMMARY_SUCCESS = 'PLEA_SUMMARY_SUCCESS';
export const PLEA_SUMMARY_FAIL = 'PLEA_SUMMARY_FAIL';

export const PLEA_CREATE_RESET = 'PLEA_CREATE_RESET';
