export const SCREEN_LIST_REQUEST = "SCREEN_LIST_REQUEST";
export const SCREEN_LIST_SUCCESS = "SCREEN_LIST_SUCCESS";
export const SCREEN_LIST_FAIL = "SCREEN_LIST_FAIL";

export const SCREEN_DETAILS_REQUEST = "SCREEN_DETAILS_REQUEST";
export const SCREEN_DETAILS_SUCCESS = "SCREEN_DETAILS_SUCCESS";
export const SCREEN_DETAILS_FAIL = "SCREEN_DETAILS_FAIL";

export const SCREEN_PIN_DETAILS_REQUEST = "SCREEN_PIN_DETAILS_REQUEST";
export const SCREEN_PIN_DETAILS_SUCCESS = "SCREEN_PIN_DETAILS_SUCCESS";
export const SCREEN_PIN_DETAILS_FAIL = "SCREEN_PIN_DETAILS_FAIL";


export const SCREEN_CREATE_REQUEST = 'SCREEN_CREATE_REQUEST';
export const SCREEN_CREATE_SUCCESS = 'SCREEN_CREATE_SUCCESS';
export const SCREEN_CREATE_FAIL = 'SCREEN_CREATE_FAIL';
export const SCREEN_CREATE_RESET = 'SCREEN_CREATE_RESET';

export const SCREEN_REVIEW_CREATE_REQUEST = 'SCREEN_REVIEW_CREATE_REQUEST';
export const SCREEN_REVIEW_CREATE_SUCCESS = 'SCREEN_REVIEW_CREATE_SUCCESS';
export const SCREEN_REVIEW_CREATE_FAIL = 'SCREEN_REVIEW_CREATE_FAIL';
export const SCREEN_REVIEW_CREATE_RESET = 'SCREEN_REVIEW_CREATE_RESET';

export const SCREEN_UPDATE_REQUEST = 'SCREEN_UPDATE_REQUEST';
export const SCREEN_UPDATE_SUCCESS = 'SCREEN_UPDATE_SUCCESS';
export const SCREEN_UPDATE_FAIL = 'SCREEN_UPDATE_FAIL';
export const SCREEN_UPDATE_RESET = 'SCREEN_UPDATE_RESET';

export const SCREEN_DELETE_REQUEST = 'SCREEN_DELETE_REQUEST';
export const SCREEN_DELETE_SUCCESS = 'SCREEN_DELETE_SUCCESS';
export const SCREEN_DELETE_FAIL = 'SCREEN_DELETE_FAIL';
export const SCREEN_DELETE_RESET = 'SCREEN_DELETE_RESET';

export const SCREEN_CATEGORY_LIST_REQUEST = 'SCREEN_CATEGORY_LIST_REQUEST';
export const SCREEN_CATEGORY_LIST_SUCCESS = 'SCREEN_CATEGORY_LIST_SUCCESS';
export const SCREEN_CATEGORY_LIST_FAIL = 'SCREEN_CATEGORY_LIST_FAIL';

export const SCREEN_VIDEOS_REQUEST = 'SCREEN_VIDEOS_REQUEST';
export const SCREEN_VIDEOS_SUCCESS = 'SCREEN_VIDEOS_SUCCESS';
export const SCREEN_VIDEOS_FAIL = 'SCREEN_VIDEOS_FAIL';

export const SCREEN_VIDEO_UPLOAD_REQUEST = 'SCREEN_VIDEO_UPLOAD_REQUEST';
export const SCREEN_VIDEO_UPLOAD_SUCCESS = 'SCREEN_VIDEO_UPLOAD_SUCCESS';
export const SCREEN_VIDEO_UPLOAD_FAIL = 'SCREEN_VIDEO_UPLOAD_FAIL';

export const SCREEN_VIDEO_DELETE_REQUEST = 'SCREEN_VIDEO_DELETE_REQUEST';
export const SCREEN_VIDEO_DELETE_SUCCESS = 'SCREEN_VIDEO_DELETE_SUCCESS';
export const SCREEN_VIDEO_DELETE_FAIL = 'SCREEN_VIDEO_DELETE_FAIL';

export const SCREEN_LIKE_REQUEST = 'SCREEN_LIKE_REQUEST';
export const SCREEN_LIKE_SUCCESS = 'SCREEN_LIKE_SUCCESS';
export const SCREEN_LIKE_FAIL = 'SCREEN_LIKE_FAIL';

export const SCREEN_UNLIKE_REQUEST = 'SCREEN_UNLIKE_REQUEST';
export const SCREEN_UNLIKE_SUCCESS = 'SCREEN_UNLIKE_SUCCESS';
export const SCREEN_UNLIKE_FAIL = 'SCREEN_UNLIKE_FAIL';

export const SCREEN_FLAG_REQUEST = 'SCREEN_FLAG_REQUEST';
export const SCREEN_FLAG_SUCCESS = 'SCREEN_FLAG_SUCCESS';
export const SCREEN_FLAG_FAIL = 'SCREEN_FLAG_FAIL';

export const SCREEN_SUBSCRIBE_REQUEST = 'SCREEN_SUBSCRIBE_REQUEST';
export const SCREEN_SUBSCRIBE_SUCCESS = 'SCREEN_SUBSCRIBE_SUCCESS';
export const SCREEN_SUBSCRIBE_FAIL = 'SCREEN_SUBSCRIBE_FAIL';

export const SCREEN_UNSUBSCRIBE_REQUEST = 'SCREEN_UNSUBSCRIBE_REQUEST';
export const SCREEN_UNSUBSCRIBE_SUCCESS = 'SCREEN_UNSUBSCRIBE_SUCCESS';
export const SCREEN_UNSUBSCRIBE_FAIL = 'SCREEN_UNSUBSCRIBE_FAIL';

export const SCREEN_ALLY_PLEA_REQUEST = 'SCREEN_ALLY_PLEA_REQUEST';
export const SCREEN_ALLY_PLEA_SUCCESS = 'SCREEN_ALLY_PLEA_SUCCESS';
export const SCREEN_ALLY_PLEA_FAIL = 'SCREEN_ALLY_PLEA_FAIL';
export const SCREEN_ALLY_PLEA_RESET = 'SCREEN_ALLY_PLEA_RESET';

export const SCREEN_ALLY_GRANT_REQUEST = 'SCREEN_ALLY_GRANT_REQUEST';
export const SCREEN_ALLY_GRANT_SUCCESS = 'SCREEN_ALLY_GRANT_SUCCESS';
export const SCREEN_ALLY_GRANT_FAIL = 'SCREEN_ALLY_GRANT_FAIL';
export const SCREEN_ALLY_GRANT_RESET = 'SCREEN_ALLY_GRANT_RESET';

export const SCREEN_ALLY_REJECT_REQUEST = 'SCREEN_ALLY_REJECT_REQUEST';
export const SCREEN_ALLY_REJECT_SUCCESS = 'SCREEN_ALLY_REJECT_SUCCESS';
export const SCREEN_ALLY_REJECT_FAIL = 'SCREEN_ALLY_REJECT_FAIL';
export const SCREEN_ALLY_REJECT_RESET = 'SCREEN_ALLY_REJECT_RESET';

export const SCREEN_PARAMS_REQUEST = 'SCREEN_PARAMS_REQUEST';
export const SCREEN_PARAMS_SUCCESS = 'SCREEN_PARAMS_SUCCESS';
export const SCREEN_PARAMS_FAIL = 'SCREEN_PARAMS_FAIL';

export const SCREEN_LOCATION_SAVE = 'SCREEN_LOCATION_SAVE';

