export const SHOP_LIST_REQUEST = "SHOP_LIST_REQUEST";
export const SHOP_LIST_SUCCESS = "SHOP_LIST_SUCCESS";
export const SHOP_LIST_FAIL = "SHOP_LIST_FAIL";

export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";

export const SHOP_CREATE_REQUEST = 'SHOP_CREATE_REQUEST';
export const SHOP_CREATE_SUCCESS = 'SHOP_CREATE_SUCCESS';
export const SHOP_CREATE_FAIL = 'SHOP_CREATE_FAIL';
export const SHOP_CREATE_RESET = 'SHOP_CREATE_RESET';

export const SHOP_REVIEW_CREATE_REQUEST = 'SHOP_REVIEW_CREATE_REQUEST';
export const SHOP_REVIEW_CREATE_SUCCESS = 'SHOP_REVIEW_CREATE_SUCCESS';
export const SHOP_REVIEW_CREATE_FAIL = 'SHOP_REVIEW_CREATE_FAIL';
export const SHOP_REVIEW_CREATE_RESET = 'SHOP_REVIEW_CREATE_RESET';

export const SHOP_UPDATE_REQUEST = 'SHOP_UPDATE_REQUEST';
export const SHOP_UPDATE_SUCCESS = 'SHOP_UPDATE_SUCCESS';
export const SHOP_UPDATE_FAIL = 'SHOP_UPDATE_FAIL';
export const SHOP_UPDATE_RESET = 'SHOP_UPDATE_RESET';

export const SHOP_DELETE_REQUEST = 'SHOP_DELETE_REQUEST';
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS';
export const SHOP_DELETE_FAIL = 'SHOP_DELETE_FAIL';
export const SHOP_DELETE_RESET = 'SHOP_DELETE_RESET';

export const SHOP_CATEGORY_LIST_REQUEST = 'SHOP_CATEGORY_LIST_REQUEST';
export const SHOP_CATEGORY_LIST_SUCCESS = 'SHOP_CATEGORY_LIST_SUCCESS';
export const SHOP_CATEGORY_LIST_FAIL = 'SHOP_CATEGORY_LIST_FAIL';

export const SHOP_ITEMS_REQUEST = 'SHOP_ITEMS_REQUEST';
export const SHOP_ITEMS_SUCCESS = 'SHOP_ITEMS_SUCCESS';
export const SHOP_ITEMS_FAIL = 'SHOP_ITEMS_FAIL';

export const SHOP_ITEM_UPLOAD_REQUEST = 'SHOP_ITEM_UPLOAD_REQUEST';
export const SHOP_ITEM_UPLOAD_SUCCESS = 'SHOP_ITEM_UPLOAD_SUCCESS';
export const SHOP_ITEM_UPLOAD_FAIL = 'SHOP_ITEM_UPLOAD_FAIL';

export const SHOP_ITEM_DELETE_REQUEST = 'SHOP_ITEM_DELETE_REQUEST';
export const SHOP_ITEM_DELETE_SUCCESS = 'SHOP_ITEM_DELETE_SUCCESS';
export const SHOP_ITEM_DELETE_FAIL = 'SHOP_ITEM_DELETE_FAIL';

export const SHOP_LIKE_REQUEST = 'SHOP_LIKE_REQUEST';
export const SHOP_LIKE_SUCCESS = 'SHOP_LIKE_SUCCESS';
export const SHOP_LIKE_FAIL = 'SHOP_LIKE_FAIL';

export const SHOP_UNLIKE_REQUEST = 'SHOP_UNLIKE_REQUEST';
export const SHOP_UNLIKE_SUCCESS = 'SHOP_UNLIKE_SUCCESS';
export const SHOP_UNLIKE_FAIL = 'SHOP_UNLIKE_FAIL';

export const SHOP_FLAG_REQUEST = 'SHOP_FLAG_REQUEST';
export const SHOP_FLAG_SUCCESS = 'SHOP_FLAG_SUCCESS';
export const SHOP_FLAG_FAIL = 'SHOP_FLAG_FAIL';

export const SHOP_PARAMS_REQUEST = 'SHOP_PARAMS_REQUEST';
export const SHOP_PARAMS_SUCCESS = 'SHOP_PARAMS_SUCCESS';
export const SHOP_PARAMS_FAIL = 'SHOP_PARAMS_FAIL';

export const SHOP_PIN_DETAILS_REQUEST = 'SHOP_PIN_DETAILS_REQUEST';
export const SHOP_PIN_DETAILS_SUCCESS = 'SHOP_PIN_DETAILS_SUCCESS';
export const SHOP_PIN_DETAILS_FAIL = 'SHOP_PIN_DETAILS_FAIL';
