export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_TOPMASTERS_LIST_REQUEST = 'USER_TOPMASTERS_LIST_REQUEST';
export const USER_TOPMASTERS_LIST_SUCCESS = 'USER_TOPMASTERS_LIST_SUCCESS';
export const USER_TOPMASTERS_LIST_FAIL = 'USER_TOPMASTERS_LIST_FAIL';

export const USER_TOPALLIES_LIST_REQUEST = 'USER_TOPALLIES_LIST_REQUEST';
export const USER_TOPALLIES_LIST_SUCCESS = 'USER_TOPALLIES_LIST_SUCCESS';
export const USER_TOPALLIES_LIST_FAIL = 'USER_TOPALLIES_LIST_FAIL';

export const USER_TOPBRANDS_LIST_REQUEST = 'USER_TOPBRANDS_LIST_REQUEST';
export const USER_TOPBRANDS_LIST_SUCCESS = 'USER_TOPBRANDS_LIST_SUCCESS';
export const USER_TOPBRANDS_LIST_FAIL = 'USER_TOPBRANDS_LIST_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_ASSETS_REQUEST = 'USER_ASSETS_REQUEST';
export const USER_ASSETS_SUCCESS = 'USER_ASSETS_SUCCESS';
export const USER_ASSETS_FAIL = 'USER_ASSETS_FAIL';

export const USER_SCREENS_REQUEST = 'USER_SCREENS_REQUEST';
export const USER_SCREENS_SUCCESS = 'USER_SCREENS_SUCCESS';
export const USER_SCREENS_FAIL = 'USER_SCREENS_FAIL';

export const USER_VIDEOS_REQUEST = 'USER_VIDEOS_REQUEST';
export const USER_VIDEOS_SUCCESS = 'USER_VIDEOS_SUCCESS';
export const USER_VIDEOS_FAIL = 'USER_VIDEOS_FAIL';

export const USER_CHANNELS_REQUEST = 'USER_CHANNELS_REQUEST';
export const USER_CHANNELS_SUCCESS = 'USER_CHANNELS_SUCCESS';
export const USER_CHANNELS_FAIL = 'USER_CHANNELS_FAIL';

export const USER_FILMS_REQUEST = 'USER_FILMS_REQUEST';
export const USER_FILMS_SUCCESS = 'USER_FILMS_SUCCESS';
export const USER_FILMS_FAIL = 'USER_FILMS_FAIL';

export const USER_SHOPS_REQUEST = 'USER_SHOPS_REQUEST';
export const USER_SHOPS_SUCCESS = 'USER_SHOPS_SUCCESS';
export const USER_SHOPS_FAIL = 'USER_SHOPS_FAIL';

export const USER_ITEMS_REQUEST = 'USER_ITEMS_REQUEST';
export const USER_ITEMS_SUCCESS = 'USER_ITEMS_SUCCESS';
export const USER_ITEMS_FAIL = 'USER_ITEMS_FAIL';