export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST';
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS';
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL';

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';

export const UPLOAD_VIDEO_REQUEST = 'UPLOAD_VIDEO_REQUEST';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAIL = 'UPLOAD_VIDEO_FAIL';
export const UPLOAD_VIDEO_RESET = 'UPLOAD_VIDEO_RESET';

export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL';
export const VIDEO_DELETE_RESET = 'VIDEO_DELETE_RESET';

export const LIKE_VIDEO_REQUEST = 'LIKE_VIDEO_REQUEST';
export const LIKE_VIDEO_SUCCESS = 'LIKE_VIDEO_SUCCESS';
export const LIKE_VIDEO_FAIL = 'LIKE_VIDEO_FAIL';

export const UNLIKE_VIDEO_REQUEST = 'LIKE_VIDEO_REQUEST';
export const UNLIKE_VIDEO_SUCCESS = 'LIKE_VIDEO_SUCCESS';
export const UNLIKE_VIDEO_FAIL = 'LIKE_VIDEO_FAIL';

export const REVIEW_VIDEO_REQUEST = 'REVIEW_VIDEO_REQUEST';
export const REVIEW_VIDEO_SUCCESS = 'REVIEW_VIDEO_SUCCESS';
export const REVIEW_VIDEO_FAIL = 'REVIEW_VIDEO_FAIL';
export const REVIEW_VIDEO_RESET = 'REVIEW_VIDEO_RESET';

export const VIEWS_VIDEO_REQUEST = 'VIEWS_VIDEO_REQUEST';
export const VIEWS_VIDEO_SUCCESS = 'VIEWS_VIDEO_SUCCESS';
export const VIEWS_VIDEO_FAIL = 'VIEWS_VIDEO_FAIL';

export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST';
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS';
export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL';
export const VIDEO_UPDATE_RESET = 'VIDEO_UPDATE_RESET';

export const VIDEO_PARAMS_REQUEST = 'VIDEO_PARAMS_REQUEST';
export const VIDEO_PARAMS_SUCCESS = 'VIDEO_PARAMS_SUCCESS';
export const VIDEO_PARAMS_FAIL = 'VIDEO_PARAMS_FAIL';

export const VIDEO_FLAG_REQUEST = 'VIDEO_FLAG_REQUEST';
export const VIDEO_FLAG_SUCCESS = 'VIDEO_FLAG_SUCCESS';
export const VIDEO_FLAG_FAIL = 'VIDEO_FLAG_FAIL';