export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAIL = 'WALLET_CREATE_FAIL';
export const WALLET_CREATE_RESET = 'WALLET_CREATE_RESET';

export const WALLET_DETAILS_REQUEST = 'WALLET_DETAILS_REQUEST';
export const WALLET_DETAILS_SUCCESS = 'WALLET_DETAILS_SUCCESS';
export const WALLET_DETAILS_FAIL = 'WALLET_DETAILS_FAIL';

export const WALLET_LIST_REQUEST = 'WALLET_LIST_REQUEST';
export const WALLET_LIST_SUCCESS = 'WALLET_LIST_SUCCESS'; 
export const WALLET_LIST_FAIL = 'WALLET_LIST_FAIL';

export const WALLET_EDIT_REQUEST = 'WALLET_EDIT_REQUEST';
export const WALLET_EDIT_SUCCESS = 'WALLET_EDIT_SUCCESS';
export const WALLET_EDIT_FAIL = 'WALLET_EDIT_FAIL';
export const WALLET_EDIT_RESET = 'WALLET_EDIT_RESET';

export const TOKENS_TRANSFER_REQUEST = 'TOKENS_TRANSFER_REQUEST';
export const TOKENS_TRANSFER_SUCCESS = 'TOKENS_TRANSFER_SUCCESS';
export const TOKENS_TRANSFER_FAIL = 'TOKENS_TRANSFER_FAIL';
export const TOKENS_TRANSFER_RESET = 'TOKENS_TRANSFER_RESET';

export const USER_ATOMIC_NFT_UPLOAD_REQUEST = 'USER_ATOMIC_NFT_UPLOAD_REQUEST';
export const USER_ATOMIC_NFT_UPLOAD_SUCCESS = 'USER_ATOMIC_NFT_UPLOAD_SUCCESS';
export const USER_ATOMIC_NFT_UPLOAD_FAIL = 'USER_ATOMIC_NFT_UPLOAD_FAIL';
export const USER_ATOMIC_NFT_UPLOAD_RESET = 'USER_ATOMIC_NFT_UPLOAD_RESET';